version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  post-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-microservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/postsdb
    depends_on:
      - mongodb

volumes:
  mongo-data:
